DEFRA/btms-gateway

BtmsGateway/appsettings.json
=> Updated ipaffs endpoints

.github/workflows/publish.yml
=> added localstack to publish yaml

.github/workflows/publish.yml
=> changed publish yaml paths

BtmsGateway.Test/Services/Routing/QueueSenderTests.cs, BtmsGateway/Middleware/MessageData.cs, BtmsGateway/Services/Routing/QueueSender.cs
This PR adds the trace header to messages pushed to SNS
=> Add trace header to SQS

.editorconfig, BtmsGateway.Test/EndToEnd/DecisionNotificationFromAlvsToIpaffsTests.cs, BtmsGateway.Test/EndToEnd/FinalisationNotificationFromAlvsToIpaffsTests.cs, BtmsGateway.Test/EndToEnd/PassThroughRequestTests.cs, BtmsGateway.Test/EndToEnd/PollSearchCertificateResultFromAlvsToIpaffsTests.cs, BtmsGateway.Test/EndToEnd/SearchCertificateFromAlvstoIpaffsTests.cs, BtmsGateway.Test/Middleware/MessageDataTests.cs, BtmsGateway.Test/Middleware/RoutingInterceptorTests.cs, BtmsGateway.Test/Services/Checking/CheckRoutesTests.cs, BtmsGateway.Test/Services/Health/HealthCheckPublisherTests.cs, BtmsGateway.Test/Services/Health/QueueHealthCheckTests.cs, BtmsGateway.Test/Services/Routing/QueueSenderTests.cs, BtmsGateway/Config/ConfigureServices.cs, BtmsGateway/Services/Checking/CheckRoutes.cs, BtmsGateway/Services/Checking/CheckRoutesEndpoints.cs, BtmsGateway/Services/Checking/ProcessRunner.cs, BtmsGateway/Services/Metrics/EmfExporter.cs, README.md
- Adds test coverage.
- Updates documentation
- Extract Network Health Check Process Runner out to a separate service
- Ensure formatting is consistent
- Some general cleanup
=> CDMS-522: Gateway cleanup and general housekeeping

.github/workflows/check-pull-request.yml, .github/workflows/publish.yml, .github/workflows/sonarcloud.yml, BtmsGateway/Middleware/MessageData.cs, BtmsGateway/Middleware/RoutingInterceptor.cs, BtmsGateway/Services/Checking/CheckRoutes.cs
- Removes logging of the entire SOAP request
- Makes some log entries Debug level entries
- Prefixes log message with MRN/Request Identifier
=> CDMS 525 logging cleanup

BtmsGateway.Test/BtmsGateway.Test.csproj, BtmsGateway.Test/Middleware/Fixtures/AlvsErrorHandling.xml, BtmsGateway.Test/Middleware/Fixtures/CdsErrorHandling.xml, BtmsGateway.Test/Middleware/Fixtures/CdsToAlvsClearanceRequest.xml, BtmsGateway.Test/Middleware/Fixtures/CdsToAlvsFinalisationNotification.xml, BtmsGateway.Test/Middleware/MessageDataTests.cs, BtmsGateway/Domain/MessagingConstants.cs, BtmsGateway/Middleware/MessageData.cs, BtmsGateway/appsettings.json, compose.yml, compose/Dockerfile.localstack, compose/start-localstack.sh
- Includes message attribute for messages published to Trade Imports Inbound Customs Declaration Received topic.
- Adds docker compose config for local testing.
=> CDMS-539: includes message attribute for messages published to new inbound topic

BtmsGateway.Test/Config/DataApiOptionsTests.cs, BtmsGateway.Test/Config/DecisionComparerApiOptionsTests.cs, BtmsGateway.Test/Consumers/ClearanceDecisionConsumerTests.cs, BtmsGateway.Test/EndToEnd/DecisionNotificationFromAlvsToCdsTests.cs, BtmsGateway.Test/EndToEnd/Fixtures/TargetRoutingConfig.json, BtmsGateway.Test/EndToEnd/GeneralEndToEndTests.cs, BtmsGateway.Test/EndToEnd/QueueRoutingTestBase.cs, BtmsGateway.Test/EndToEnd/Settings/ConsumerSettings.json, BtmsGateway.Test/EndToEnd/TargetRoutingTestBase.cs, BtmsGateway.Test/Services/Routing/ApiSenderTests.cs, BtmsGateway.Test/Services/Routing/DecisionSenderTests.cs, BtmsGateway.Test/Services/Routing/MessageRouterTests.cs, BtmsGateway.Test/TestUtils/TestWebServer.cs, BtmsGateway.Test/Utils/Logging/ReadOnlyDictionaryExtensionsTests.cs, BtmsGateway/Config/ConfigureServices.cs, BtmsGateway/Config/DecisionComparerApiOptions.cs, BtmsGateway/Consumers/ClearanceDecisionConsumer.cs, BtmsGateway/Domain/MessagingConstants.cs, BtmsGateway/Exceptions/DecisionComparisonException.cs, BtmsGateway/Middleware/MessageData.cs, BtmsGateway/Middleware/RoutingInterceptor.cs, BtmsGateway/Services/Routing/ApiSender.cs, BtmsGateway/Services/Routing/DecisionSender.cs, BtmsGateway/Services/Routing/MessageRouter.cs, BtmsGateway/Services/Routing/RoutingConfig.cs, BtmsGateway/Utils/Http/Proxy.cs, BtmsGateway/appsettings.Development.json, BtmsGateway/appsettings.json, compose/start-localstack.sh
- Updates BTMS decision consumer to send BTMS decision to comparer and no longer sends decision to stub
- Updates ALVS decision forking to send decision to comparer
- Decision response from comparer logged and not sent to stub
- Fixes some compiler warnings
=> Cdms 527 integrate decision comparator api

BtmsGateway.Test/Services/Routing/DecisionSenderTests.cs, BtmsGateway/Services/Routing/DecisionSender.cs
- Fixes the result returned by fork processing so that the resulting log message correctly reflects the processing
=> CDMS-527: fix fork result logging

BtmsGateway.Test/Config/DataApiOptionsTests.cs, BtmsGateway.Test/Config/DecisionComparerApiOptionsTests.cs, BtmsGateway.Test/Services/Health/TopicHealthCheckTests.cs, BtmsGateway/Config/DataApiOptions.cs, BtmsGateway/Config/DecisionComparerApiOptions.cs, BtmsGateway/Config/HttpClientConfigurableOptions.cs, BtmsGateway/Extensions/ServiceCollectionExtensions.cs, BtmsGateway/Program.cs, BtmsGateway/Services/Health/ApiHealthCheck.cs, BtmsGateway/Services/Health/ConfigureHealthChecks.cs, BtmsGateway/Services/Health/QueueHealthCheck.cs, BtmsGateway/Services/Health/TopicHealthCheck.cs, BtmsGateway/Utils/Http/Proxy.cs
-adds health check against dependent SNS Topics, SQS Queues, Data API and Decision Comparer API.
=> CDMS-580: adds health check against dependent components

BtmsGateway.Test/Services/Health/HealthCheckPublisherTests.cs, BtmsGateway.Test/Services/Metrics/HealthMetricsTests.cs, BtmsGateway.Test/Services/Metrics/MetricsTestBase.cs, BtmsGateway/Extensions/ServiceCollectionExtensions.cs, BtmsGateway/Services/Health/HealthCheckPublisher.cs, BtmsGateway/Services/Health/QueueHealthCheck.cs, BtmsGateway/Services/Metrics/HealthMetrics.cs, BtmsGateway/Services/Metrics/MetricsConstants.cs
- Publishes health metrics for the application as well as it's dependencies
=> CDMS-660: publish health metrics

BtmsGateway/BtmsGateway.csproj, BtmsGateway/Extensions/ConsumerContextExtensions.cs, BtmsGateway/Extensions/ServiceCollectionExtensions.cs, BtmsGateway/Utils/Logging/LoggingInterceptor.cs
Updated Defra.TradeImportsDataApi.Api.Client
Added logging interceptor to help with trace is being attached to errors
=> Added logging interceptor 

BtmsGateway.Test/Services/Health/TopicHealthCheckTests.cs, BtmsGateway/Services/Health/ApiHealthCheck.cs, BtmsGateway/Services/Health/QueueHealthCheck.cs, BtmsGateway/Services/Health/TopicHealthCheck.cs
=> CDMS-580: sets status to Unhealthy if internal dependencies don't report successful communication

BtmsGateway/Config/AwsSqsOptions.cs, BtmsGateway/Extensions/AmazonConsumerExtensions.cs
- Adds configurable option for setting the number of consumers per host (defaulted to 20 per host)
=> Adds configurable consumer counts

BtmsGateway/Middleware/RoutingInterceptor.cs
=> Check action link type when logging route not found

BtmsGateway/Extensions/ServiceCollectionExtensions.cs, BtmsGateway/Program.cs, BtmsGateway/Utils/Logging/LoggingInterceptor.cs, BtmsGateway/Utils/Logging/TraceContextEnricher.cs
This PR replicates the following PRs made in the processor:
- PR https://github.com/DEFRA/trade-imports-processor/pull/126
- PR https://github.com/DEFRA/trade-imports-processor/pull/127
- PR https://github.com/DEFRA/trade-imports-processor/pull/128
- PR https://github.com/DEFRA/trade-imports-processor/pull/129
=> Replicate changes made in processor

BtmsGateway.Test/BtmsGateway.Test.csproj, BtmsGateway/BtmsGateway.csproj
=> Update deps where safe

BtmsGateway.Test/Middleware/RoutingInterceptorTests.cs, BtmsGateway.Test/Services/Metrics/RequestMetricsTests.cs, BtmsGateway/Middleware/RoutingInterceptor.cs, BtmsGateway/Services/Metrics/MetricsConstants.cs, BtmsGateway/Services/Metrics/RequestMetrics.cs
- Emits metrics for successfully routed messages for use in Grafana to compare received vs successfully sent
=> CDMS-769: emits metrics for successfully routed messages

.config/dotnet-tools.json
- Updates version of csharpier. This change was originally raised by Dependabot but that PR was closed in favour of applying this change separately due to strange Dependabot suggestions
=> Updating csharpier tool version

BtmsGateway.Test/Services/Routing/DifferentMessageTypesOnSameRouteTests.cs, BtmsGateway.Test/Services/Routing/ErrorNotificationSenderTests.cs, BtmsGateway.Test/Services/Routing/MessageRouterTests.cs, BtmsGateway.Test/Services/Routing/MessageRoutesTests.cs, BtmsGateway/Consumers/ClearanceDecisionConsumer.cs, BtmsGateway/Consumers/ProcessingErrorConsumer.cs, BtmsGateway/Middleware/MessageData.cs, BtmsGateway/Services/Routing/DecisionSender.cs, BtmsGateway/Services/Routing/ErrorNotificationSender.cs, BtmsGateway/Services/Routing/MessageRouter.cs, BtmsGateway/Services/Routing/MessageRoutes.cs
- Adds MRN and correlation id prefix on all related log entries where it is available and applicable
- Temporarily removes the functionality which sends Error Notifications to CDS (Jira Ticket CDMS-520) to allow this logging feature to be deployed to Prod first. CDMS-520 has been pulled back to In Progress in Jira so the feature doesn't get lost
=> Cdms 840 include mrn prefix on all log messages when available

BtmsGateway.Test/TestUtils/TestWebServer.cs
This change is needed for a subsequent change about to be made.
It's being made in isolation to show it does not affect existing code.
Updating dependencies has revealed test transient failures when multiple tests are run at the same time. Despite tests within a fixture being run sequentially by default. There are several places where race conditions could exist within how the gateway tests are written. These need updating but they are outside the scope of this current ticket.
Therefore, for now, we accept we might have a task be cancelled during disposal and this is OK.
=> Allow TestWebServer dispose flow to skip TaskCanceledException

BtmsGateway/appsettings.Development.json, compose.yml, compose/dotnet-service.env, compose/wiremock/mappings/ComparerApiResponses.json, tests/BtmsGateway.IntegrationTests/BtmsGateway.IntegrationTests.csproj, tests/BtmsGateway.IntegrationTests/Data/Entities/Notification.cs, tests/BtmsGateway.IntegrationTests/EndToEnd/Decisions/DecisionsTests.cs, tests/BtmsGateway.IntegrationTests/EndToEnd/Errors/OutboundErrorsTests.cs, tests/BtmsGateway.IntegrationTests/Endpoints/Admin/AdminTests.cs, tests/BtmsGateway.IntegrationTests/TestBase/IntegrationTestBase.cs, tests/BtmsGateway.IntegrationTests/Utils/Http/ProxyTests.cs
- Brings CDS Simulator into the docker compose stack
- Updates connections accordingly
- Updates tests where setup requires the use of Wiremock
- Updates tests to assert on CDS Simulator DB records
=> CDMS-1130: integrate with CDS Simulator
