- BtmsGateway.Test/Middleware/MessageDataTests.cs
- BtmsGateway.Test/Services/Routing/MessageRoutesTests.cs
- BtmsGateway.Test/Services/Routing/RoutingConfigTests.cs
- BtmsGateway.Test/Services/Routing/TestRoutes.cs
- BtmsGateway/BtmsGateway.csproj
- BtmsGateway/Middleware/MessageData.cs
- BtmsGateway/Middleware/RoutingInterceptor.cs
- BtmsGateway/Services/Checking/CheckRouteConfig.cs
- BtmsGateway/Services/Checking/CheckRoutes.cs
- BtmsGateway/Services/Routing/MessageRouter.cs
- BtmsGateway/Services/Routing/MessageRoutes.cs
- BtmsGateway/Services/Routing/RoutingConfig.cs
- BtmsGateway/Services/Routing/RoutingResult.cs
- BtmsGateway/appsettings.json
- Dockerfile
- run.sh
It turns out there is standard HTTP way to solve the issue of the URL (an IP address here) not matching the DNS name on the certificate. You need to set the header called "host" which is supported in .NET. That means it does not need the hosts file entry to match IP to DNS. It should not need the certificates to be installed as they are standard, publicly available root/intermediate certs, though that is a config thing we will discover after initial deployment.
Used the opportunity to add unit tests to a particularly complex area which highlighted some edge case weaknesses, now plugged, particularly around the use on the "Accept" header.
> CDMS 216 Connect to IBM T2 using IP

- BtmsGateway.Test/EndToEnd/DecisionNotificationFromAlvsToIpaffsTests.cs
- BtmsGateway.Test/EndToEnd/Fixtures/AlvsToIpaffsPollSearchCertificateResult.xml
- BtmsGateway.Test/EndToEnd/Fixtures/TargetRoutingConfig.json
- BtmsGateway.Test/EndToEnd/PollSearchCertificateResultFromAlvsToIpaffsTests.cs
- BtmsGateway/appsettings.json
The previous routes added did work, but we were also missing pollSearchCertificateResult.  This has now been added.
> Added missing pollSearchCertificateResult route and matching tests.

- BtmsGateway.Test/Services/Converter/ClearanceDecisionToSoapConverterTests.cs
- BtmsGateway.Test/Services/Converter/Fixtures/ClearanceDecisionSoap.xml
- BtmsGateway/Services/Converter/ClearanceDecisionToSoapConverter.cs
- makes decision reason on the outbound soap message an unbounded array of elements instead of a single concatenation of the reason strings.
> CDMS-527: makes decision reason an array of elements

- BtmsGateway.Test/Consumers/ClearanceDecisionConsumerTests.cs
- BtmsGateway.Test/Services/Routing/DecisionSenderTests.cs
- BtmsGateway.Test/Services/Routing/MessageRouterTests.cs
- BtmsGateway/BtmsGateway.csproj
- BtmsGateway/Config/ConfigureServices.cs
- BtmsGateway/Consumers/ClearanceDecisionConsumer.cs
- BtmsGateway/Domain/Features.cs
- BtmsGateway/Services/Routing/DecisionSender.cs
- BtmsGateway/Services/Routing/MessageRouter.cs
- BtmsGateway/appsettings.Development.json
- BtmsGateway/appsettings.json
- Feature flagged functionality to only send BTMS decisions to CDS during testing
- ALVS decision will be persisted to Decision Comparer but not forwarded onto CDS
> CDMS-629 send only BTMS decision to CDS in test

- BtmsGateway.Test/BtmsGateway.Test.csproj
- BtmsGateway.Test/Consumers/ClearanceDecisionConsumerTests.cs
- BtmsGateway.Test/EndToEnd/EndToEndTestCollection.cs
- BtmsGateway.Test/EndToEnd/GeneralEndToEndTests.cs
- BtmsGateway.Test/EndToEnd/TargetRoutingTestBase.cs
- BtmsGateway.sln.DotSettings
- BtmsGateway/BtmsGateway.csproj
- BtmsGateway/Consumers/ClearanceDecisionConsumer.cs
As per PR title.
This is just enough code for now to allow us to create a subscription rule of the gateway so it will receive inbound errors.
> Discard inbound error sub resource type if received

- BtmsGateway.Test/Consumers/ClearanceDecisionConsumerTests.cs
- BtmsGateway.Test/Consumers/ConsumerMediatorTests.cs
- BtmsGateway.Test/EndToEnd/EndToEndTestCollection.cs
- BtmsGateway.Test/EndToEnd/GeneralEndToEndTests.cs
- BtmsGateway.Test/EndToEnd/TargetRoutingTestBase.cs
- BtmsGateway.Test/TestUtils/AsyncWaiter.cs
- BtmsGateway.Test/TestUtils/TestWebServer.cs
- BtmsGateway/Consumers/ClearanceDecisionConsumer.cs
- BtmsGateway/Consumers/ConsumerMediator.cs
- BtmsGateway/Extensions/AmazonConsumerExtensions.cs
- BtmsGateway/Extensions/ConsumerContextExtensions.cs
Back our previous logic that handled the InboundError sub resource type, however still allow processing of the main customs declaration, which is only acted on if the clearance decision is being created/updated.
Add mediator consumer that allows different resource events to be processed.
Add a wait within the `TestWebServer` construction logic that polls the /health endpoint and will only proceed once it's successful. Hopefully this will reduce flakiness of tests in pipeline.
> Temp handling of processing errors and only handle ClearanceDecision sub resource type of a CustomsDeclaration resource event

- BtmsGateway.Test/Services/Health/NetworkHealthCheckTests.cs
- BtmsGateway/Services/Checking/CheckRouteConfig.cs
- BtmsGateway/Services/Health/NetworkHealthCheck.cs
- BtmsGateway/appsettings.json
Health check against an external HMRC route is showing as Degraded because we are receiving HTTP Status 405 back from the test.
This should be considered successful because the GET request was specifically configured so as not to cause issues on HMRC.
This change allows for configuration to control certain Status codes being considered as successful on a per route definition basis.
> Configures health check to allow specific statuses on particular routes.

- BtmsGateway.Test/BtmsGateway.Test.csproj
- BtmsGateway.Test/Services/Converter/Fixtures/ClearanceRequestWithXmlCharacterEntityValues.xml
- BtmsGateway.Test/Services/Converter/Fixtures/DecisionNotificationWithHtmlEncoding.xml
- BtmsGateway.Test/Services/Converter/SoapContentTests.cs
- BtmsGateway.Test/Services/Converter/SoapToJsonConverterTests.cs
- BtmsGateway/Services/Converter/SoapContent.cs
- HTML Decodes ALVS to CDS Decision Notification and HMRC Error Notification only before passing the raw string into an XML Document
- All other messages are not HTML Decoded
> CDMS-637: handles html decoding of relevant messages

- BtmsGateway.Test/Services/Converter/Fixtures/ClearanceDecisionSoap.xml
- BtmsGateway/Services/Converter/ClearanceDecisionToSoapConverter.cs
- Decision Notifications created from BTMS Clearance Decisions have a default "000" correlation id
- Fixes an error in the timestamp format to include milliseconds
> Defaults correlation id on SOAP messages created from BTMS Clearance Decisions.

- BtmsGateway.Test/Services/Metrics/HealthMetricsTests.cs
- BtmsGateway/Services/Metrics/HealthMetrics.cs
- Theory test to try fixing one Panel in Grafana that isn't receiving metrics. All Panels work in the Dev environment. In Test, there is one Panel that doesn't appear to be receiving data. Confirmed the same service code is deployed and CDP Support have checked the Panel code as well as the Cloudwatch Metrics. The broken Panel does have different content dimension in Test so testing whether removing this has any effect. The dimension is not currently used in the Panels anyway.
> CDMS-660: remove content dimension to test panel fix

- BtmsGateway/appsettings.json
- Default appsettings uses Stub health checks which don't require the host header configuration. These will be specified in the relevant cdp-app-config environment configuration.
> CDMS-744: removes the host header config for stubbed health checks

- BtmsGateway/Services/Metrics/HealthMetrics.cs
- Removes Info level logging following successful identification of the metrics issue. Reduces the amount of noise in our logs.
> CDMS-660: remove info logging following successful identification of the metrics issue

- BtmsGateway/Domain/MessagingConstants.cs
- BtmsGateway/Middleware/MessageData.cs
To be able to include generic logging around message consumption within the BTMS pipeline, this PR includes the EntryReference as a ResourceId header, which downstream services can then use.
> Map and include ResourceId header to EntryReference

- BtmsGateway.Test/Http/ProxyTest.cs
- BtmsGateway.Test/TestUtils/TestWebServer.cs
- BtmsGateway/Config/ConfigureServices.cs
- BtmsGateway/Extensions/ServiceCollectionExtensions.cs
- BtmsGateway/Program.cs
- BtmsGateway/Utils/Http/Proxy.cs
- BtmsGateway/Utils/TrustStore.cs
As per PR title.
We have observed that logs made during startup do not report correctly within CDP. As these logs provide minimal to no value anyway, we are getting rid of them.
Any Fatal failure to startup will be caught and logged by the try/catch around the startup process.
We now include the `EcsTextFormatter` in the reloadable bootstrap logger that is created during startup to try and avoid logs reaching CDP that are in the incorrect format.
As the end to end tests do not startup an actual gateway host using `Program.cs`, only some of the configuration is triggered, which means the logging setup does not get exercised in full.
The end to end tests are due to be refactored so they are not in memory and are running within a contained Docker environment as our other services are. But …
> Remove logger during startup

- BtmsGateway/Extensions/ConsumerContextExtensions.cs
- BtmsGateway/Utils/Logging/LoggingInterceptor.cs
- BtmsGateway/Utils/Logging/WebApplicationBuilderExtensions.cs
As per PR title.
Also included an amend to the configure logging method to remove the `integrationTest` param as it's not used and gives the impression it's consumed in tests, which is not the case.
> Add ResourceId into the logging, which will be included if present

- BtmsGateway.Test/Consumers/ClearanceDecisionConsumerTests.cs
- BtmsGateway.Test/Consumers/ProcessingErrorConsumerTests.cs
- BtmsGateway.Test/Services/Routing/DecisionSenderTests.cs
- BtmsGateway.Test/Services/Routing/ErrorNotificationSenderTests.cs
- BtmsGateway/Consumers/ClearanceDecisionConsumer.cs
- BtmsGateway/Consumers/ProcessingErrorConsumer.cs
- BtmsGateway/Exceptions/ConflictException.cs
- BtmsGateway/Services/Routing/DecisionSender.cs
- BtmsGateway/Services/Routing/ErrorNotificationSender.cs
- BtmsGateway/Services/Routing/SoapMessageSenderBase.cs
- BtmsGateway/Utils/Logging/LoggingInterceptor.cs
- Throws custom exception when a 409 conflict occurs so that it can be caught and logged as warning as the exception is bubbled up
- Refactoring to satisfy sonar
> Cdms 851 log 409 as warnings

- BtmsGateway.Test/Services/Routing/QueueSenderTests.cs
- BtmsGateway/Services/Converter/SoapUtils.cs
- BtmsGateway/Services/Routing/QueueSender.cs
- When BTMS becomes the primary route for HMRC CDS requests going to ALVS, then Gateway needs to respond with a successful SOAP response if the request is successfully received and published to our Inbound Topic
> CDMS-418: returning successful responses for HRMC requests when primary routing is going to BTMS backend topic

- BtmsGateway.Test/Middleware/RoutingInterceptorTests.cs
- BtmsGateway.Test/Services/Converter/SoapContentTests.cs
- BtmsGateway.Test/Services/Converter/SoapToJsonConverterTests.cs
- BtmsGateway.Test/Services/Routing/MessageRoutesTests.cs
- BtmsGateway.Test/Services/Routing/QueueSenderTests.cs
- BtmsGateway.Test/Services/Routing/TestRoutes.cs
- BtmsGateway/Domain/Features.cs
- BtmsGateway/Domain/MessagingConstants.cs
- BtmsGateway/Exceptions/InvalidSoapException.cs
- BtmsGateway/Middleware/RoutingInterceptor.cs
- BtmsGateway/Services/Converter/SoapContent.cs
- BtmsGateway/Services/Converter/SoapToJsonConverter.cs
- BtmsGateway/Services/Converter/SoapUtils.cs
- BtmsGateway/Services/Routing/DecisionSender.cs
- BtmsGateway/Services/Routing/ErrorNotificationSender.cs
- BtmsGateway/Services/Routing/MessageRoutes.cs
- BtmsGateway/Services/Routing/QueueSender.cs
- BtmsGateway/Services/Routing/RoutingConfig.cs
- BtmsGateway/appsettings.json
- Checks for SOAP exceptions in requests sent from CDS and returns a relevant SOAP response during cutover phase, otherwise returns whatever it is currently returning
- Also checks for failures to publish to the inbound SNS Topic and returns a relevant SOAP response during cutover phase
> CDMS-808: return SOAP failure responses

- BtmsGateway/Services/Routing/MessageRoutes.cs
- Provides a default response to requests that are configured to be routed to 'None' (the discard route)
> CDMS-978: provides a positive response to ALVS IPAFFS requests that are routed to None and discarded.

- compose.yml
The healthcheck port was incorrect in the compose file.
> BAU: Fix healthcheck port for the gateway

- BtmsGateway/Services/Routing/DecisionSender.cs
- BtmsGateway/Services/Routing/ErrorNotificationSender.cs
- BtmsGateway/Services/Routing/SoapMessageSenderBase.cs
- In the message Consumers, when the template field 'CorrelationId' is used in a log message template, it was being replaced by the TraceContextEnricher with the Trace ID. This fix uses a different template field to avoid the clash.
> CDMS-1013: fix log templating where correlation id is used

- BtmsGateway/Config/ConfigureServices.cs
- BtmsGateway/Services/Routing/ApiSender.cs
- BtmsGateway/Services/Routing/MessageRoutes.cs
- BtmsGateway/Services/Routing/RoutingConfig.cs
- BtmsGateway/Services/Routing/RoutingResult.cs
- BtmsGateway/Utils/Http/Proxy.cs
- BtmsGateway/appsettings.IntegrationTests.json
- BtmsGateway/appsettings.json
- tests/BtmsGateway.IntegrationTests/BtmsGateway.IntegrationTests.csproj
- tests/BtmsGateway.IntegrationTests/Fixtures/SearchCertificate.xml
- tests/BtmsGateway.IntegrationTests/Utils/Http/ProxyTests.cs
- Allows for configuration of routes to use a specific named HTTP Client
- Provides a named HTTP Client specifically for ALVS to IPAFFS Search and Poll Search requests
- This client is configured with longer request timeout (defaulted to 100 seconds which was used before Cutover)
> CDMS-1058: uses http client with a longer timeout for specifically configured routes (ALVS to IPAFFS search requests)
